{
  "openapi": "3.0.0",
  "info": {
    "title": "ZohoIM",
    "version": "1.0.0",
    "description": "API specification for ZohoIM"
  },
  "servers": [
    {
      "url": "https://im.localzoho.com",
      "description": "API Server"
    }
  ],
  "paths": {
    "/api/v1/cannedMessages": {
      "get": {
        "summary": "Get existing canned messages",
        "tags": [
          "ZohoIM"
        ]
      },
      "post": {
        "summary": "Create a new canned messsage",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "De-Activate a Canned Message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/cannedMessages/([0-9]+)": {
      "patch": {
        "summary": "Update a canned message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get detailed information of a canned message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a canned message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/cannedMessages/([0-9]+)/activation": {
      "patch": {
        "summary": "Activate a Canned Message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "De-Activate a Canned Message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/templateMessages/sync": {
      "post": {
        "summary": "Sync Template Message From Whatsapp",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/cannedMessages/([0-9]+)/translations/([0-9]+)": {
      "get": {
        "summary": "Get a single canned message translation for a Canned Message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a canned message translation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a canned message translation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/cannedMessages/([0-9]+)/translations": {
      "get": {
        "summary": "Get all translations for a Canned Message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a canned message translation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/internalapi/kafkaMeta": {
      "get": {
        "summary": "Get Kafka Meta of IM Service",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/bundle/([0-9]+)/serviceorg": {
      "get": {
        "summary": "Get Linked IM Portal of given Bundle Service",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/serviceOrganizations": {
      "post": {
        "summary": "Link Commerce ZohoService org with IM Org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/serviceOrganizations/([0-9]+)": {
      "delete": {
        "summary": "Remove linking of Commerce ZohoService org from IM Org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/zohoservices": {
      "get": {
        "summary": "Get IM Supported Zoho services",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/organizations/bundle/associate": {
      "post": {
        "summary": "Upgrade Standalone IM org to Bundle",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/organizations/bundle": {
      "delete": {
        "summary": "Downgrade Bundle Org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/organizations/bundle/subscription": {
      "patch": {
        "summary": "To update subscription changes on bundle",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/internalapi/organizations/bundle/disassociate": {
      "patch": {
        "summary": "Disassociate IM org from Bundle",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/api/v1/pns/installationId": {
      "get": {
        "summary": "To get a InstallationId for a device",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/pns/register": {
      "post": {
        "summary": "To register a device for push notifications",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "To un-register a device for push notifications",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/organizations": {
      "get": {
        "summary": "Get IM Organizations of an User",
        "tags": [
          "ZohoIM"
        ],
        
      },
      "post": {
        "summary": "Create an IM Orgniazation",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/organizations/([0-9]+)": {
      "get": {
        "summary": "Get details of an IM Org",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/serviceOrganizations": {
      "post": {
        "summary": "Link other ZohoService org with IM Org",
        "tags": [
          "ZohoIM"
        ],
        
      },
      "get": {
        "summary": "Get zoho service organizations linked with an IM Org",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/serviceOrganizations/([0-9]+)": {
      "delete": {
        "summary": "Remove linking of other ZohoService org from IM Org",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/migrateDC": {
      "post": {
        "summary": "Remove linking of other ZohoService org from IM Org",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/integrations": {
      "get": {
        "summary": "Get list of available integrations to add as channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([a-zA-Z0-9\\-]+)": {
      "get": {
        "summary": "Get detailed information     of a specific Integration",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/accounts": {
      "get": {
        "summary": "Get twilio subaccount details for this org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/purchasedNumbers": {
      "get": {
        "summary": "Get Purchased Phone Numbers in Twilio Subaccount",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/releaseNumber/([0-9]+)": {
      "patch": {
        "summary": "To release the whatsapp phone number from twilio",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/numbers": {
      "get": {
        "summary": "Get Available Phone Numbers,Country,Number Type for Purchase from Twilio",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create twilio subaccount for this org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([a-zA-Z0-9\\-]+)/configParams/([a-zA-Z0-9_]+)/computeOptions": {
      "post": {
        "summary": "Compute config params with parent params",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/configParams/([a-zA-Z0-9_]+)/computeOptions": {
      "post": {
        "summary": "Compute config params with parent params",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels": {
      "get": {
        "summary": "Get existing channels",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a new channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)": {
      "patch": {
        "summary": "Update channel info and config params",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get detailed information of a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/activate": {
      "patch": {
        "summary": "Activate a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "De-Activate a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/count": {
      "get": {
        "summary": "Channels count",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/subscribers": {
      "get": {
        "summary": "Get list of subscribers of a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add a subscriber (other zoho service org) to the channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Remove a subscriber (other zoho service org) from the channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/configParams": {
      "get": {
        "summary": "Get config param details of a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update config param values of a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/configParams/([a-zA-Z0-9_]+)": {
      "get": {
        "summary": "Get single config param detail",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/meta": {
      "get": {
        "summary": "GET Channel Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Save Channel Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/preferences": {
      "get": {
        "summary": "Get existing channels",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a Channel Preference",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete all preferences of a Channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/preferences": {
      "get": {
        "summary": "Get existing channels",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/sdk/efc": {
      "get": {
        "summary": "Get EFC Script",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/contacts": {
      "get": {
        "summary": "Get list of Contacts",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/contacts/([0-9]+)": {
      "get": {
        "summary": "Get detailed information of a contact",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Upadte a contact",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/profiles": {
      "get": {
        "summary": "Get list of integration user profiles",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/profiles/([0-9]+)": {
      "get": {
        "summary": "Get detailed information of a user profile",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions": {
      "get": {
        "summary": "Get list of conversations with filters",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessionsWithLastMessages": {
      "get": {
        "summary": "Get list of conversations with filters along with LastMessages",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/([0-9]+)": {
      "get": {
        "summary": "Get detailed information of a conversation",
        "tags": [
          "ZohoIM"
        ],
        
      },
      "patch": {
        "summary": "Update conversation status",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/metrics": {
      "get": {
        "summary": "Get session metrics for all channels or get metrics for specific channel",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/endInActive": {
      "post": {
        "summary": "End inactive sessions",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/([0-9]+)/meta": {
      "get": {
        "summary": "GET Session Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Save Session Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/participants": {
      "get": {
        "summary": "Get list of conversation participants",
        "tags": [
          "ZohoIM"
        ],
        
      },
      "post": {
        "summary": "Add participants to a conversation",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/([0-9]+)/removeParticipants": {
      "post": {
        "summary": "Remove participants from a conversation",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/([0-9]+)/markAsRead": {
      "patch": {
        "summary": "Mark the conversation as read by an agent until the given message id",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/([0-9]+)/updateMessageConsumptionStatus": {
      "patch": {
        "summary": "mark the message as consumed, pushed through realtime",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/sessions/lastMessages": {
      "post": {
        "summary": "Fetch last messages of a conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/messagesByMeta": {
      "post": {
        "summary": "Fetch messages of a conversation matching given meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages": {
      "get": {
        "summary": "Fetch messages of a conversation with filters",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add message to a particular conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/sessions/([a-zA-Z0-9]+)/messages": {
      "get": {
        "summary": "Fetch messages of a conversation with filters",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add message to a particular channel conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/initiateSession": {
      "post": {
        "summary": "Initiate New Conversation in a channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/layoutMessageWithCannedId": {
      "post": {
        "summary": "Add message to a particular conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/layoutMessage": {
      "post": {
        "summary": "Add message to a particular conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/attachments": {
      "post": {
        "summary": "Send attachment to a particular conversation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get attachments under a session",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)/resend": {
      "post": {
        "summary": "Retry a failed message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)": {
      "delete": {
        "summary": "Delete a failed message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get detailed information of a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)/meta": {
      "get": {
        "summary": "GET Message Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Save Message Meta",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)/action": {
      "post": {
        "summary": "Perform action on a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)/fullContent": {
      "get": {
        "summary": "Get full content of a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/messages/([0-9]+)/rawContent": {
      "get": {
        "summary": "Get raw content of a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/search": {
      "get": {
        "summary": "Get list of conversations with SearchKey",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages,contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/messages/search": {
      "get": {
        "summary": "Get list of Conversations with SearchKey",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/contacts/search": {
      "get": {
        "summary": "Get list of Contacts with SearchKey",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "contacts"
            ]
          }
        ]
      }
    },
    "/api/v1/metrics/conversation/timeseries": {
      "get": {
        "summary": "Get Conversation based metrics",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/metrics/messages/timeseries": {
      "get": {
        "summary": "Get Message based metrics",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/metrics/sessions/timeseries": {
      "get": {
        "summary": "Get Session based metrics",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/metrics/payment/timeseries": {
      "get": {
        "summary": "Get Payment based metrics",
        "tags": [
          "ZohoIM"
        ],
        
      }
    },
    "/api/v1/metrics/agents": {
      "get": {
        "summary": "Get Agent's Performance metrics",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/fbManager/([a-zA-Z0-9]+)": {
      "post": {
        "summary": "get IM portal using the fb account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "patch": {
        "summary": "get IM portal using the fb account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "get": {
        "summary": "get IM portals and services using this fb business manager account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "delete mapped fbBmId and twilio SID for this IM portal",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/fbManager": {
      "get": {
        "summary": "Get mapped FB Business manager account for this org",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WECOM/auth": {
      "post": {
        "summary": "To submit the Wecom on-boarding data form",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WECOM/csaccounts": {
      "post": {
        "summary": "To create Wechat Customer Service Account - on Wecom Channel Creation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "get": {
        "summary": "To get Wechat Customer Service Accounts - on Wecom Channel Creation",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WECOM/license": {
      "post": {
        "summary": "To purchase Wecom Account License for the organization",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/TWILIO/requestAccess": {
      "post": {
        "summary": "To submit the whatsapp on-boarding data in creator form",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/sandBoxTesters": {
      "post": {
        "summary": "To get and verify phoneNumber's OTP",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/phonenumbers/([0-9]+)/codeVerification": {
      "post": {
        "summary": "To get and verify phoneNumber's OTP",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/templateTags": {
      "post": {
        "summary": "To get supported Whatsapp template message categories list",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/templateLanguages": {
      "post": {
        "summary": "To get supported Whatsapp template message categories list",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/token": {
      "post": {
        "summary": "To get and verify phoneNumber's OTP",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/details": {
      "post": {
        "summary": "To get Details of WABA",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/account/([0-9]+)/catalog": {
      "post": {
        "summary": "Connect catalog with waba",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Disconnect catalog from waba",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/phonenumber/([0-9]+)/catalog": {
      "post": {
        "summary": "cart and catalog should be visible or not for business phone number",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/twoStepVerification": {
      "post": {
        "summary": "To enable/disable two step verification",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/profileAbout": {
      "post": {
        "summary": "To update whatsapp - about profile",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/profileAbout/(\\+[0-9]+)": {
      "get": {
        "summary": "Get whatsapp - about profile",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/profilePhoto/(\\+[0-9]+)": {
      "get": {
        "summary": "Get whatsapp - about profile",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Update profile photo",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/obaRequest/(\\+[0-9]+)": {
      "post": {
        "summary": "Request Official Business Account (Green tick badge)",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/templateCreditExhaustStatus": {
      "post": {
        "summary": "To check template credit exhausted for the passed receivernumber",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/phonenumbers": {
      "get": {
        "summary": "Get all whatsapp phone numbers",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/businessAccounts": {
      "get": {
        "summary": "Get all mapped WABA",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/businessAccounts/([0-9]+)": {
      "delete": {
        "summary": "Remove WABA from IM",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/account/([0-9]+)/migrate": {
      "post": {
        "summary": "Migrate Phone Number to WABA",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/templateSync": {
      "post": {
        "summary": "template message sync",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/WHATSAPP/broadcast/pricing": {
      "post": {
        "summary": "To check template credit exhausted for the passed receiver numbers wrt to country",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([A-Z]+)/channels/([0-9]+)/webhookInfo": {
      "get": {
        "summary": "Get configured webhook",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([A-Z]+)/channels/([0-9]+)/botInfo": {
      "get": {
        "summary": "Get bot details",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/subscription/addOn": {
      "get": {
        "summary": "Get configured or active subscription details",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Buy credits pack for an integration",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update credits pack for an integration. Enable/disable auto renewal / update renewal package count or renewal threshold count ",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/subscription/statement": {
      "get": {
        "summary": "To get Payment statement of IM Credits for a particular organization",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/subscription/license": {
      "get": {
        "summary": "Get configured or active subscription details",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/subscription/migrateToNewLicense": {
      "post": {
        "summary": "Migrate Twilio number to new licensing model",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([a-zA-Z0-9\\-]+)/parentAccounts": {
      "get": {
        "summary": "Get Integration service Parent Account List",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add Integration service Parent Account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([a-zA-Z0-9\\-]+)/parentAccounts/([0-9]+)": {
      "patch": {
        "summary": "Update Integration service Parent Account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Integration service Parent Account",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/integrations/([a-zA-Z0-9\\-]+)/authUrl": {
      "get": {
        "summary": "Get Authentication Url for parent Accounts or channel",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/createdBy": {
      "patch": {
        "summary": "update createdBy in entities",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels"
            ]
          }
        ]
      }
    },
    "/api/v1/channels/([0-9]+)/messages": {
      "post": {
        "summary": "update createdBy in entities",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/broadcasts": {
      "post": {
        "summary": "Create a new broadcast",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get list of broadcast",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/campaigns": {
      "post": {
        "summary": "Create a new broadcast",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/broadcasts/([0-9]+)": {
      "get": {
        "summary": "Get a broadcast",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "DELETE a broadcast",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/broadcasts/([0-9]+)/details": {
      "get": {
        "summary": "Get broadcast metrics",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/broadcasts/([0-9]+)/receivers": {
      "get": {
        "summary": "Get broadcast receivers",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/broadcasts/summary": {
      "get": {
        "summary": "Get broadcast metrics",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "channels,messages"
            ]
          }
        ]
      }
    },
    "/api/v1/organizations/owner": {
      "patch": {
        "summary": "update organization createdBy",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations,users"
            ]
          }
        ]
      }
    },
    "/api/v1/migration/messages": {
      "post": {
        "summary": "Get detailed information of a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/sessions/([0-9]+)/attachments/([0-9]+)": {
      "get": {
        "summary": "Get attachment of a message",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/attachments/([a-zA-Z0-9]+)": {
      "get": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/attachments/([0-9]+)": {
      "get": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/attachments/([0-9]+)/data": {
      "get": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/attachments/format": {
      "get": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/api/v1/attachments": {
      "post": {
        "summary": "Get attachment",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    },
    "/internalapi/export": {
      "post": {
        "summary": "Export Details",
        "tags": [
          "ZohoIM"
        ],
        "security": [
          {
            "OAuth2": [
              "messages"
            ]
          }
        ]
      }
    }
  },
  "components": {
  }
}
