openapi: 3.0.0
info:
  title: ZohoIM
  version: 1.0.0
  description: >-
      ZohoIM abstracts the difficulties in integrating various Instant Messaging Channels by Providing an Unified API.
      ### Communicate with your customers through any Instant Messaging Channel
      <img src="https://content.pstmn.io/001c6190-9c45-4b0f-87cb-6c1043f209cd/aW1hZ2UucG5n" /> <br><br><br>
      
      **Why Zoho IM?**
      Most of the support channels often bring layers of complexities - IM manages all these interactions into a single connected system.
      Our focus was on improving agent productivity with an intuitive approach and compatible interface.
      Our seamless integration with customers' best-loved platforms such as WhatsApp, Telegram, LINE, WeChat and Facebook Messenger.
      <br><br>
      **Getting Started** <br>
      - All Zoho IM APIs require these two mandatory fields in the header. <br>
      - Authorization - Authentication request token <br>
      - orgId -ID of the organization to access. All API endpoints except /organizations mandatorily require the orgId. <br>

      
      <img src="https://content.pstmn.io/7ba8a04d-b133-46e2-8d4c-633a5bc57378/ZXpnaWYuY29tLXZpZGVvLXRvLWdpZiAoMSkuZ2lm" /> <br><br>
      For detailed flow of Authorization [visit](https://www.zoho.com/accounts/protocol/oauth/self-client/authorization-code-flow.html)
      <br><br>
      **Steps (refer the above gif):** <br>
      - Sign into https://www.accounts.zoho.com <br>
      - Go to [Zoho Developer Console](https://api-console.zoho.com/) -> Add Client <br>
      - Choose Self Client  <br>
      - Note down Client ID and Client Secret under Client Secret Tab <br>
      - Under Generate Code - Provide scopes, time duration and desciption  <br>
      - Choose create which will provide a code.  <br>
      <br><br>
      **Scopes:** <br>
      - ZohoIM.organizations.ALL <br>
      - ZohoIM.channels.ALL <br>
      - ZohoIM.conversations.ALL  <br>
      - ZohoIM.messages.ALL <br>
      - ZohoIM.bots.ALL <br>
      - ZohoIM.users.ALL  <br>
      - ZohoIM.contacts.ALL <br>
      - ZohoIM.search.READ  <br>
      <br><br>
      **Note:**
      - Access token should be prefixed with the prefix "Zoho-oauthtoken" <br>
        Example token, **Zoho-oauthtoken 1000.dfe95e72e98e1657****
servers:
  - url: https://im.localzoho.com
    description: Local Zoho Server
  - url: http://127.0.0.1:3000
    description: Mock Server
paths:
  /api/v1/cannedMessages:
    get:
      summary: Get existing canned messages
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 60
    post:
      summary: Create a new canned messsage
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 5M
          threshold: 100
    delete:
      summary: De-Activate a Canned Message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/cannedMessages/([0-9]+):
    patch:
      summary: Update a canned message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
    get:
      summary: Get detailed information of a canned message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 50
    delete:
      summary: Delete a canned message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
  /api/v1/cannedMessages/([0-9]+)/activation:
    patch:
      summary: Activate a Canned Message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
    delete:
      summary: De-Activate a Canned Message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/templateMessages/sync:
    post:
      summary: Sync Template Message From Whatsapp
      tags:
        - Templatemessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
  /api/v1/cannedMessages/([0-9]+)/translations/([0-9]+):
    get:
      summary: Get a single canned message translation for a Canned Message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
    delete:
      summary: Delete a canned message translation
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
    patch:
      summary: Update a canned message translation
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/cannedMessages/([0-9]+)/translations:
    get:
      summary: Get all translations for a Canned Message
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
    post:
      summary: Create a canned message translation
      tags:
        - Cannedmessages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 5M
          threshold: 100
  /api/v1/sessions/([0-9]+)/attachments/([0-9]+):
    get:
      summary: Get attachment of a message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /api/v1/attachments/([a-zA-Z0-9]+):
    get:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /api/v1/attachments/([0-9]+):
    get:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
    delete:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /api/v1/attachments/([0-9]+)/data:
    get:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /api/v1/attachments/format:
    get:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /api/v1/attachments:
    post:
      summary: Get attachment
      tags:
        - Attachments
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /internalapi/export:
    post:
      summary: Export Details
      tags:
        - Internalapi
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 60
  /internalapi/kafkaMeta:
    get:
      summary: Get Kafka Meta of IM Service
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /internalapi/bundle/([0-9]+)/serviceorg:
    get:
      summary: Get Linked IM Portal of given Bundle Service
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /internalapi/serviceOrganizations:
    post:
      summary: Link Commerce ZohoService org with IM Org
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 5M
          threshold: 5
        - duration: 1H
          lockPeriod: 20M
          threshold: 20
  /internalapi/serviceOrganizations/([0-9]+):
    delete:
      summary: Remove linking of Commerce ZohoService org from IM Org
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1H
          threshold: 5
        - duration: 1H
          lockPeriod: 20M
          threshold: 20
  /internalapi/zohoservices:
    get:
      summary: Get IM Supported Zoho services
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /internalapi/organizations/bundle/associate:
    post:
      summary: Upgrade Standalone IM org to Bundle
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 10
  /internalapi/organizations/bundle:
    delete:
      summary: Downgrade Bundle Org
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 10
  /internalapi/organizations/bundle/subscription:
    patch:
      summary: To update subscription changes on bundle
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 20
  /internalapi/organizations/bundle/disassociate:
    patch:
      summary: Disassociate IM org from Bundle
      tags:
        - Internalapi
      security: []
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 10
  /api/v1/pns/installationId:
    get:
      summary: To get a InstallationId for a device
      tags:
        - Pns
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
  /api/v1/pns/register:
    post:
      summary: To register a device for push notifications
      tags:
        - Pns
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
    delete:
      summary: To un-register a device for push notifications
      tags:
        - Pns
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
  /api/v1/organizations:
    get:
      summary: Get IM Organizations of an User
      tags:
        - Organizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
    post:
      summary: Create an IM Orgniazation
      tags:
        - Organizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 1H
          threshold: 5
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/organizations/([0-9]+):
    get:
      summary: Get details of an IM Org
      tags:
        - Organizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
  /api/v1/serviceOrganizations:
    post:
      summary: Link other ZohoService org with IM Org
      tags:
        - Serviceorganizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 1H
          threshold: 5
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
    get:
      summary: Get zoho service organizations linked with an IM Org
      tags:
        - Serviceorganizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 5
  /api/v1/serviceOrganizations/([0-9]+):
    delete:
      summary: Remove linking of other ZohoService org from IM Org
      tags:
        - Serviceorganizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 1H
          threshold: 5
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/migrateDC:
    post:
      summary: Remove linking of other ZohoService org from IM Org
      tags:
        - Migratedc
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 1H
          threshold: 5
  /api/v1/integrations:
    get:
      summary: Get list of available integrations to add as channel
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
  /api/v1/integrations/([a-zA-Z0-9\-]+):
    get:
      summary: Get detailed information    of a specific Integration
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
  /api/v1/integrations/TWILIO/accounts:
    get:
      summary: Get twilio subaccount details for this org
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 60
  /api/v1/integrations/TWILIO/purchasedNumbers:
    get:
      summary: Get Purchased Phone Numbers in Twilio Subaccount
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1D
          lockPeriod: 10M
          threshold: 60
  /api/v1/integrations/TWILIO/releaseNumber/([0-9]+):
    patch:
      summary: To release the whatsapp phone number from twilio
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/TWILIO/numbers:
    get:
      summary: Get Available Phone Numbers,Country,Number Type for Purchase from Twilio
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1D
          lockPeriod: 10M
          threshold: 100
    post:
      summary: Create twilio subaccount for this org
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1D
          lockPeriod: 10M
          threshold: 25
  /api/v1/integrations/([a-zA-Z0-9\-]+)/configParams/([a-zA-Z0-9_]+)/computeOptions:
    post:
      summary: Compute config params with parent params
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 25
  /api/v1/channels/([0-9]+)/configParams/([a-zA-Z0-9_]+)/computeOptions:
    post:
      summary: Compute config params with parent params
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 25
  /api/v1/channels:
    get:
      summary: Get existing channels
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 60
    post:
      summary: Create a new channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/channels/([0-9]+):
    patch:
      summary: Update channel info and config params
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
    get:
      summary: Get detailed information of a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 60
    delete:
      summary: Delete a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
  /api/v1/channels/([0-9]+)/activate:
    patch:
      summary: Activate a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
    delete:
      summary: De-Activate a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/channels/count:
    get:
      summary: Channels count
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 60
  /api/v1/channels/([0-9]+)/subscribers:
    get:
      summary: Get list of subscribers of a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    post:
      summary: Add a subscriber (other zoho service org) to the channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    delete:
      summary: Remove a subscriber (other zoho service org) from the channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/channels/([0-9]+)/configParams:
    get:
      summary: Get config param details of a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 30
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
    patch:
      summary: Update config param values of a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 15
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
  /api/v1/channels/([0-9]+)/configParams/([a-zA-Z0-9_]+):
    get:
      summary: Get single config param detail
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 30
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
  /api/v1/channels/([0-9]+)/meta:
    get:
      summary: GET Channel Meta
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    patch:
      summary: Save Channel Meta
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/channels/([0-9]+)/preferences:
    get:
      summary: Get existing channels
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    patch:
      summary: Update a Channel Preference
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    delete:
      summary: Delete all preferences of a Channel
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 10
  /api/v1/channels/preferences:
    get:
      summary: Get existing channels
      tags:
        - Channels
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sdk/efc:
    get:
      summary: Get EFC Script
      tags:
        - Sdk
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 10M
          threshold: 50
  /api/v1/contacts:
    get:
      summary: Get list of Contacts
      tags:
        - Contacts
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 150
  /api/v1/contacts/([0-9]+):
    get:
      summary: Get detailed information of a contact
      tags:
        - Contacts
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
    patch:
      summary: Upadte a contact
      tags:
        - Contacts
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 10
        - duration: 1d
          lockPeriod: 1d
          threshold: 15
  /api/v1/profiles:
    get:
      summary: Get list of integration user profiles
      tags:
        - Profiles
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 20
  /api/v1/profiles/([0-9]+):
    get:
      summary: Get detailed information of a user profile
      tags:
        - Profiles
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
  /api/v1/sessions:
    get:
      summary: Get list of conversations with filters
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/sessionsWithLastMessages:
    get:
      summary: Get list of conversations with filters along with LastMessages
      tags:
        - Sessionswithlastmessages
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/sessions/([0-9]+):
    get:
      summary: Get detailed information of a conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 25
    patch:
      summary: Update conversation status
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 200
  /api/v1/sessions/metrics:
    get:
      summary: Get session metrics for all channels or get metrics for specific channel
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/sessions/endInActive:
    post:
      summary: End inactive sessions
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 250
  /api/v1/sessions/([0-9]+)/meta:
    get:
      summary: GET Session Meta
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    patch:
      summary: Save Session Meta
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sessions/([0-9]+)/participants:
    get:
      summary: Get list of conversation participants
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 250
    post:
      summary: Add participants to a conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 250
  /api/v1/sessions/([0-9]+)/removeParticipants:
    post:
      summary: Remove participants from a conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 250
  /api/v1/sessions/([0-9]+)/markAsRead:
    patch:
      summary: Mark the conversation as read by an agent until the given message id
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 60
  /api/v1/sessions/([0-9]+)/updateMessageConsumptionStatus:
    patch:
      summary: mark the message as consumed, pushed through realtime
      tags:
        - Sessions
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 60
  /api/v1/sessions/lastMessages:
    post:
      summary: Fetch last messages of a conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 30
  /api/v1/sessions/messagesByMeta:
    post:
      summary: Fetch messages of a conversation matching given meta
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 30
  /api/v1/sessions/([0-9]+)/messages:
    get:
      summary: Fetch messages of a conversation with filters
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 30
    post:
      summary: Add message to a particular conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/channels/([0-9]+)/sessions/([a-zA-Z0-9]+)/messages:
    get:
      summary: Fetch messages of a conversation with filters
      tags:
        - Channels
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 30
    post:
      summary: Add message to a particular channel conversation
      tags:
        - Channels
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/channels/([0-9]+)/initiateSession:
    post:
      summary: Initiate New Conversation in a channel
      tags:
        - Channels
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sessions/([0-9]+)/layoutMessageWithCannedId:
    post:
      summary: Add message to a particular conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/sessions/([0-9]+)/layoutMessage:
    post:
      summary: Add message to a particular conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/sessions/([0-9]+)/attachments:
    post:
      summary: Send attachment to a particular conversation
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
    get:
      summary: Get attachments under a session
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sessions/([0-9]+)/messages/([0-9]+)/resend:
    post:
      summary: Retry a failed message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sessions/([0-9]+)/messages/([0-9]+):
    delete:
      summary: Delete a failed message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    get:
      summary: Get detailed information of a message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
  /api/v1/sessions/([0-9]+)/messages/([0-9]+)/meta:
    get:
      summary: GET Message Meta
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
    patch:
      summary: Save Message Meta
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 30
  /api/v1/sessions/([0-9]+)/messages/([0-9]+)/action:
    post:
      summary: Perform action on a message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
  /api/v1/sessions/([0-9]+)/messages/([0-9]+)/fullContent:
    get:
      summary: Get full content of a message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 6
  /api/v1/sessions/([0-9]+)/messages/([0-9]+)/rawContent:
    get:
      summary: Get raw content of a message
      tags:
        - Sessions
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 2M
          threshold: 100
  /api/v1/search:
    get:
      summary: Get list of conversations with SearchKey
      tags:
        - Search
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/messages/search:
    get:
      summary: Get list of Conversations with SearchKey
      tags:
        - Messages
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/contacts/search:
    get:
      summary: Get list of Contacts with SearchKey
      tags:
        - Contacts
      security:
        - OAuth2:
            - contacts
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/metrics/conversation/timeseries:
    get:
      summary: Get Conversation based metrics
      tags:
        - Metrics
      security:
        - OAuth2:
            - conversations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/metrics/messages/timeseries:
    get:
      summary: Get Message based metrics
      tags:
        - Metrics
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/metrics/sessions/timeseries:
    get:
      summary: Get Session based metrics
      tags:
        - Metrics
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/metrics/payment/timeseries:
    get:
      summary: Get Payment based metrics
      tags:
        - Metrics
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/metrics/agents:
    get:
      summary: Get Agent's Performance metrics
      tags:
        - Metrics
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/TWILIO/fbManager/([a-zA-Z0-9]+):
    post:
      summary: get IM portal using the fb account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    patch:
      summary: get IM portal using the fb account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    get:
      summary: get IM portals and services using this fb business manager account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 60
    delete:
      summary: delete mapped fbBmId and twilio SID for this IM portal
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/TWILIO/fbManager:
    get:
      summary: Get mapped FB Business manager account for this org
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/WECOM/auth:
    post:
      summary: To submit the Wecom on-boarding data form
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
  /api/v1/integrations/WECOM/csaccounts:
    post:
      summary: To create Wechat Customer Service Account - on Wecom Channel Creation
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 20
    get:
      summary: To get Wechat Customer Service Accounts - on Wecom Channel Creation
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 20
  /api/v1/integrations/WECOM/license:
    post:
      summary: To purchase Wecom Account License for the organization
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 20
  /api/v1/integrations/TWILIO/requestAccess:
    post:
      summary: To submit the whatsapp on-boarding data in creator form
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/WHATSAPP/sandBoxTesters:
    post:
      summary: To get and verify phoneNumber's OTP
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/WHATSAPP/phonenumbers/([0-9]+)/codeVerification:
    post:
      summary: To get and verify phoneNumber's OTP
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/WHATSAPP/templateTags:
    post:
      summary: To get supported Whatsapp template message categories list
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/WHATSAPP/templateLanguages:
    post:
      summary: To get supported Whatsapp template message categories list
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/WHATSAPP/token:
    post:
      summary: To get and verify phoneNumber's OTP
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 30
  /api/v1/integrations/WHATSAPP/details:
    post:
      summary: To get Details of WABA
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/WHATSAPP/account/([0-9]+)/catalog:
    post:
      summary: Connect catalog with waba
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 2H
          threshold: 100
    delete:
      summary: Disconnect catalog from waba
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 2H
          threshold: 100
  /api/v1/integrations/WHATSAPP/phonenumber/([0-9]+)/catalog:
    post:
      summary: cart and catalog should be visible or not for business phone number
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 2H
          threshold: 100
  /api/v1/integrations/WHATSAPP/twoStepVerification:
    post:
      summary: To enable/disable two step verification
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/WHATSAPP/profileAbout:
    post:
      summary: To update whatsapp - about profile
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/WHATSAPP/profileAbout/(\+[0-9]+):
    get:
      summary: Get whatsapp - about profile
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/WHATSAPP/profilePhoto/(\+[0-9]+):
    get:
      summary: Get whatsapp - about profile
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
    post:
      summary: Update profile photo
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/integrations/WHATSAPP/obaRequest/(\+[0-9]+):
    post:
      summary: Request Official Business Account (Green tick badge)
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/integrations/WHATSAPP/templateCreditExhaustStatus:
    post:
      summary: To check template credit exhausted for the passed receivernumber
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/integrations/WHATSAPP/phonenumbers:
    get:
      summary: Get all whatsapp phone numbers
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/WHATSAPP/businessAccounts:
    get:
      summary: Get all mapped WABA
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/WHATSAPP/businessAccounts/([0-9]+):
    delete:
      summary: Remove WABA from IM
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/WHATSAPP/account/([0-9]+)/migrate:
    post:
      summary: Migrate Phone Number to WABA
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
  /api/v1/integrations/WHATSAPP/templateSync:
    post:
      summary: template message sync
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
  /api/v1/integrations/WHATSAPP/broadcast/pricing:
    post:
      summary: >-
        To check template credit exhausted for the passed receiver numbers wrt
        to country
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/([A-Z]+)/channels/([0-9]+)/webhookInfo:
    get:
      summary: Get configured webhook
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/integrations/([A-Z]+)/channels/([0-9]+)/botInfo:
    get:
      summary: Get bot details
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
        - duration: 1H
          lockPeriod: 10M
          threshold: 50
        - duration: 1d
          lockPeriod: 1d
          threshold: 100
  /api/v1/subscription/addOn:
    get:
      summary: Get configured or active subscription details
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
    post:
      summary: Buy credits pack for an integration
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    patch:
      summary: >-
        Update credits pack for an integration. Enable/disable auto renewal /
        update renewal package count or renewal threshold count 
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/subscription/statement:
    get:
      summary: To get Payment statement of IM Credits for a particular organization
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/subscription/license:
    get:
      summary: Get configured or active subscription details
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/subscription/migrateToNewLicense:
    post:
      summary: Migrate Twilio number to new licensing model
      tags:
        - Subscription
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 30
  /api/v1/integrations/([a-zA-Z0-9\-]+)/parentAccounts:
    get:
      summary: Get Integration service Parent Account List
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
    post:
      summary: Add Integration service Parent Account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/([a-zA-Z0-9\-]+)/parentAccounts/([0-9]+):
    patch:
      summary: Update Integration service Parent Account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    delete:
      summary: Delete Integration service Parent Account
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/integrations/([a-zA-Z0-9\-]+)/authUrl:
    get:
      summary: Get Authentication Url for parent Accounts or channel
      tags:
        - Integrations
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
  /api/v1/createdBy:
    patch:
      summary: update createdBy in entities
      tags:
        - Createdby
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
  /api/v1/channels/([0-9]+)/messages:
    post:
      summary: update createdBy in entities
      tags:
        - Channels
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/broadcasts:
    post:
      summary: Create a new broadcast
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
    get:
      summary: Get list of broadcast
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/campaigns:
    post:
      summary: Create a new broadcast
      tags:
        - Campaigns
      security:
        - OAuth2:
            - channels
  /api/v1/broadcasts/([0-9]+):
    get:
      summary: Get a broadcast
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
    delete:
      summary: DELETE a broadcast
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/broadcasts/([0-9]+)/details:
    get:
      summary: Get broadcast metrics
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/broadcasts/([0-9]+)/receivers:
    get:
      summary: Get broadcast receivers
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/broadcasts/summary:
    get:
      summary: Get broadcast metrics
      tags:
        - Broadcasts
      security:
        - OAuth2:
            - channels
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/organizations/owner:
    patch:
      summary: update organization createdBy
      tags:
        - Organizations
      security:
        - OAuth2:
            - organizations
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
  /api/v1/migration/messages:
    post:
      summary: Get detailed information of a message
      tags:
        - Migration
      security:
        - OAuth2:
            - messages
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 50
  /api/v1/botServices:
    get:
      summary: Get list of available integrations to add as bot
      tags:
        - Botservices
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
  /api/v1/botServices/([a-zA-Z0-9\-\_]+):
    get:
      summary: Get detailed information     of a specific bot Integration
      tags:
        - Botservices
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 90
  /api/v1/botServices/([a-zA-Z0-9\-\_]+)/configParams/([a-zA-Z0-9_]+)/computeOptions:
    post:
      summary: Compute config params with parent params
      tags:
        - Botservices
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 180
  /api/v1/bots/([0-9]+)/configParams/([a-zA-Z0-9_]+)/computeOptions:
    post:
      summary: Compute config params with parent params
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 180
  /api/v1/bots:
    get:
      summary: Get existing bots
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 20
        - duration: 1H
          lockPeriod: 10M
          threshold: 60
    post:
      summary: Create a new bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/bots/([0-9]+):
    patch:
      summary: To update name and external Id of the bot of a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
    get:
      summary: Get detailed information of a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
    delete:
      summary: Delete a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 15
        - duration: 1H
          lockPeriod: 10M
          threshold: 45
  /api/v1/bots/([0-9]+)/activate:
    patch:
      summary: Activate a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
    delete:
      summary: De-Activate a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/bots/([0-9]+)/associate:
    patch:
      summary: Associate bot with Channels
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/bots/([0-9]+)/dissociate:
    patch:
      summary: dissocaite bot from channels
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1d
          lockPeriod: 1d
          threshold: 20
  /api/v1/bots/([0-9]+)/preferences:
    get:
      summary: get bot preferences
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 15
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
    patch:
      summary: save preferences of a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 15
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
  /api/v1/bots/([0-9]+)/configParams:
    get:
      summary: Get config param details of a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 30
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
    patch:
      summary: Update config param values of a bot
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1H
          lockPeriod: 10M
          threshold: 15
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
  /api/v1/bots/([0-9]+)/configParams/([a-zA-Z0-9_]+):
    get:
      summary: Get single config param detail
      tags:
        - Bots
      security:
        - OAuth2:
            - bots
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 30
        - duration: 1d
          lockPeriod: 1d
          threshold: 60
  /api/v1/users:
    get:
      summary: Get all users
      tags:
        - Users
      security:
        - OAuth2:
            - users
      x-throttling:
        - duration: 1M
          lockPeriod: 1M
          threshold: 60
    post:
      summary: Add a new User
      tags:
        - Users
      security:
        - OAuth2:
            - users
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
  /api/v1/users/([0-9]+):
    get:
      summary: Get a User
      tags:
        - Users
      security:
        - OAuth2:
            - users
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    patch:
      summary: Update a User
      tags:
        - Users
      security:
        - OAuth2:
            - users
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
    delete:
      summary: Add a new User
      tags:
        - Users
      security:
        - OAuth2:
            - users
      x-throttling:
        - duration: 1M
          lockPeriod: 3M
          threshold: 10
        - duration: 1H
          lockPeriod: 10M
          threshold: 20
        - duration: 1d
          lockPeriod: 1d
          threshold: 30
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth/authorize
          scopes:
            messages: Access to messages
            organizations: Access to organization data
            channels: Access to organization data
            contacts: Access to Contacts data
            conversations: Access to Conversation data
            users: Access to Users data
